// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm2-X5cyLi1N_BxdgPXqiUs6ueT1ZElLg',
    appId: '1:1010694656841:web:da2031ab869a33998b8098',
    messagingSenderId: '1010694656841',
    projectId: 'nudge-beta-app',
    authDomain: 'nudge-beta-app.firebaseapp.com',
    storageBucket: 'nudge-beta-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMKkQKFfNlmHYb9Kqrj6t50ZosO0dsu5A',
    appId: '1:1010694656841:android:065eddf0a5712d428b8098',
    messagingSenderId: '1010694656841',
    projectId: 'nudge-beta-app',
    storageBucket: 'nudge-beta-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9akBKApu3Jp-mBo3Iu2GGfes22EfzcBM',
    appId: '1:1010694656841:ios:141db1f1922869038b8098',
    messagingSenderId: '1010694656841',
    projectId: 'nudge-beta-app',
    storageBucket: 'nudge-beta-app.firebasestorage.app',
    iosBundleId: 'com.example.nudge1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9akBKApu3Jp-mBo3Iu2GGfes22EfzcBM',
    appId: '1:1010694656841:ios:141db1f1922869038b8098',
    messagingSenderId: '1010694656841',
    projectId: 'nudge-beta-app',
    storageBucket: 'nudge-beta-app.firebasestorage.app',
    iosBundleId: 'com.example.nudge1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm2-X5cyLi1N_BxdgPXqiUs6ueT1ZElLg',
    appId: '1:1010694656841:web:b33dc4f72c60b33c8b8098',
    messagingSenderId: '1010694656841',
    projectId: 'nudge-beta-app',
    authDomain: 'nudge-beta-app.firebaseapp.com',
    storageBucket: 'nudge-beta-app.firebasestorage.app',
  );

}